apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: doks-flask
  namespace: dev
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: doks-flask
  service:
    port: 80
  analysis:
    interval: 30s
    threshold: 5
    maxWeight: 50
    stepWeight: 10
    metrics:
    - name: request-success-rate
      thresholdRange: { min: 99 }
      interval: 30s
    - name: request-duration
      thresholdRange: { max: 500 }
      interval: 30s
    webhooks:
    - name: load-test
      type: pre-rollout
      url: http://flagger-loadtester.dev/
      timeout: 5s
      metadata:
        cmd: "hey -z 20s -q 10 http://doks-flask.dev/"
