apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: demo-k8s-store
spec:
  provider:
    kubernetes:
      remoteNamespace: external-secrets
      auth:
        serviceAccount:
          name: default
          namespace: prod
