apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-creds
  namespace: prod
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: demo-k8s-store
    kind: ClusterSecretStore
  target:
    name: db-creds
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef: { key: db_username }
  - secretKey: password
    remoteRef: { key: db_password }
